{% set name = "compressed-tensors" %}
{% set version = "0.15.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a8e93054e8a5ec49c980b09ed36c4c1249b4a8ee167920a8e461c4da26e78d99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm ==8.2.0
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=1.7.0
    - transformers >=4.45.0
    - pydantic >=2.0
    - loguru
    - psutil
test:
  imports:
    - compressed_tensors
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/neuralmagic/compressed-tensors
  summary: Library for utilization of compressed safetensors of neural network models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - maresb
