{% set name = "compressed-tensors" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 95ddf19699f775df6494dd864e5f52e8a24f8015496520190c1a22c6cfc44b1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm ==8.2.0
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=1.7.0
    - transformers
    - pydantic >=2.0
    - frozendict

test:
  imports:
    - compressed_tensors
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/neuralmagic/compressed-tensors
  summary: Library for utilization of compressed safetensors of neural network models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - maresb
